#!/bin/sh

rm -rf config.* src/Makevars

for i in README src/TAGS src/BROWSE demo/*.pdf inst/cxx-ex/*.o inst/cxx-ex/*.out \
	 demo/myeloid.multi.state.R vignettes/wbart.Rmd vignettes/jss.* \
	 vignettes/*.aux vignettes/*.bbl vignettes/*.blg vignettes/*.log vignettes/*.out \
	 vignettes/*.tex vignettes/*.tpt vignettes/*.pdf vignettes/*.md  vignettes/*.html  \
	 R/dpm*bart.R man/dpm*bart.Rd src/*dp*.* inst/cxx-ex/*dp*.* demo/fat.tail.dpm*.R \
	 inst/bootcamp/*
do
    if [ -f $i ]
       then rm -rf $i
    fi
done
